# Generated by Django 2.2.9 on 2020-01-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='商品编号')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='商品名称')),
                ('number', models.IntegerField(verbose_name='商品数量')),
                ('price', models.FloatField(verbose_name='商品单价')),
                ('total', models.FloatField(verbose_name='商品总价')),
            ],
            options={
                'db_table': 'shopinfo',
            },
        ),
    ]
