# Generated by Django 2.2.9 on 2020-01-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.IntegerField(verbose_name='商品单价'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='total',
            field=models.IntegerField(verbose_name='商品总价'),
        ),
    ]
