# Generated by Django 2.2.9 on 2020-01-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200102_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='total',
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9999, max_digits=7, verbose_name='商品单价'),
        ),
    ]
