# Generated by Django 2.2.9 on 2020-01-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('phone', models.IntegerField(max_length=11, verbose_name='手机号')),
                ('mail', models.EmailField(max_length=20, verbose_name='邮箱')),
                ('password', models.CharField(default=0.0, max_length=16, verbose_name='用户密码')),
                ('data', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
